### ISSUE TITLE
Feature: 3 tags per file

### ISSUE THREAD

**Issue by mhkull** [mpogue2/SquareDesk#38] opened 2017-04-11 12:11 UTC
In order to work with a larger number of files it would be of great help, to be able to add tags to files like: opener, workshop, closer, fast, smooth, morden, country ....

**Comment by danlyke** [comment] 2017-04-11 14:36
I'd like a tagging thing too. The front page is already getting pretty crowded (which is why I added the "View->Compact" menu option, for my little netbook that I use to call), so I haven't been sure how to do this. One possibility: Another tab for the currently playing song that has meta information, and then a pop-up dialog that lets you search by that meta info? Maybe making the "Type" field search that meta info as well?

**Comment by mhkull** [comment] 2017-04-12 07:21
Using the files meta tags is IMHO the best way to do it.

The only alternative I can think of is a directory solution. patter and subdirectories. However the automatic loop is only set to patter not its subdirectories. With this subdirectory solution you can select via the theme field - it works.

**Comment by danlyke** [comment] 2017-04-12 23:05
So just musing out-loud: Some sort of right-clickable dialog that lets you put in text that gets appended to the "Type", those tags can then be used for searching and in the "what type of song is this?" controls?

**Comment by mpogue2** [comment] 2017-05-06 04:36
Other suggestions for tags have been made:  "high energy", "needs work"

**Comment by mpogue2** [comment] 2018-01-14 22:36
Another way to do this, similar to what was suggested above:  Allow tagging of a file, but instead of having a separate mechanism/columns, tagged files have a symbolic link created in the same directory where they are, and THAT becomes searchable via the type column.

For example, if there's <root>/singing/Winter Wonderland.mp3, then it shows up as singing type.  Adding the tag "Christmas" would create a subdirectory in singing called "Christmas", with a symbolic link to <root>/singing/Winter Wonderland.mp3.  It would need to inherit the song settings of the root file, rather than having a separate set.  Maybe this could be simple:  when double clicking on a file that is a symbolic link, it just opens up the original file.

Right clicking would allow assigning tags to individual files, based on known tags.

This would allow us to have only a single copy of each MP3 file, but would allow any number of tags, with the existing type mechanism.

**Comment by mpogue2** [comment] 2018-02-11 03:06
Couple of ideas that we talked about:
View > Tags > Irish, Energy, etc.
View > Tags > Check all, Uncheck all
Tags show up in smaller font, with a colored background (start with white on grey, or similar)
tags show up after the title, not in their own column
entry is via Context menu (right click)
To search, use normal text in the title search field, e.g. "Summer Irish" would match "Summer Sound" with an "Irish" tag.

**Comment by danlyke** [comment] 2018-03-05 03:40
Take a look at 5eef088c45b1f5c6812c139a7739036d963da6c4 . It just allows you to append text to the end of the title for each song. It shows up in a different color (right now it's reddish). I need to make searching work by breaking the words and then searching for subsequent substrings, but this is at least something that's broken that we can fix.

**Comment by danlyke** [comment] 2018-03-05 04:46
Okay, 8e444170fdcee86ae3003abb68cea84e2a2e48e6 does the search for subsequent substrings thing.

**Comment by danlyke** [comment] 2018-03-05 05:32
Oh, I should note the mechanism: Right-click on a song, select "Edit Tags ...", get a pop-up with a text input.

**Comment by danlyke** [comment] 2018-03-06 18:46
Enhancement I need to add: Make it so we don't match the "<font color="... text that's inserted into the title, and make it so that any of the tags match no matter their order; the order stuff only counts for the title itself.

**Comment by danlyke** [comment] 2018-03-07 23:55
Okay, I realized that tags should be searchable in any order, so a91823029c8a6abb0c383257bec2d363a4b57354 allows that. It also strips the "<font color=..." stuff so that searching on "font" or "color" no longer gives false positives.

**Comment by danlyke** [comment] 2018-03-08 18:37
Okay, bd4ed3bcf56ef7f389877b0d1a980a951da9b13d solves the double-click problem that I introduced when I changed that table widget to a label in order to get the rich text.

**Comment by danlyke** [comment] 2018-03-08 20:15
85a62b0b5578c73b13bac4cadee9b909ae967906 has a background color for tags...

**Comment by danlyke** [comment] 2018-03-08 23:11
Okay. We should choose a better (and stock) set of default background colors, but 7073c0803be152aa0e263e2e9c2223de5c4e8dca adds foreground and backgrounds selection on the main prefs page.

(Kinda freaky to add a preference. I'd forgotten that I'd had all of that automated preprocessor stuff, so I was like "okay, where do I add the saving and the... oh, right. Magic.")

**Comment by mpogue2** [comment] 2018-03-10 03:15
OK, I finally have a chance to play with these!  They are looking better and better!
**Bugs:**
- I changed the FG color, and all of the fonts in the Title column went to "tiny".  Cmd-0 brought them back to correct size.
- Tags are not currently persistent on Mac OS X at least...

**Features:**
- I am really hoping that each tag will have a separate FG/BG color.  So, e.g. Irish would be white on green, etc.  I think this means having a new Tags dialog box, or a Tags tab in Preferences, to be able to set these for each tag.
- "Edit tag ..." --> "Edit tag..."  (get rid of the extra space?)
- Is there a way to do rounded corners on the tags in the Title column?  This is a minor wish.
- The tags should ideally be in a somewhat smaller font.
- For assigning tags, it would be nice to have a pulldown menu of the existing tags, that could be "checked off" to add a tag, or "New tag..." to pull up the new tag dialog...I think this would work better than the string currently used.

Overall, I am really looking forward to this feature...I find that I want to use it already!

**Comment by danlyke** [comment] 2018-03-10 17:09
On Sat, 10 Mar 2018 03:15:12 +0000 (UTC)
Mike Pogue <notifications@github.com> wrote:
> OK, I finally have a chance to play with these!  They are looking
> better and better! **Bugs:**
> - I changed the FG color, and all of the fonts in the Title column
> went to "tiny".  Cmd-0 brought them back to correct size.

Okay, that's kinda weird. I suspect that there's something about the
text edit that's going wrong.

> - Tags are not currently persistent on Mac OS X at least...

We need to figure this out. It's working on Linux. They're going into
the "tags" field of the "songs" table, though I did have one situation
where I lost tags, but I was doing enough dev stuff that I might have
nuked my database on that platform and started again.

> **Features:**
> - I am really hoping that each tag will have a separate FG/BG color.
> So, e.g. Irish would be white on green, etc.  I think this means
> having a new Tags dialog box, or a Tags tab in Preferences, to be
> able to set these for each tag.

Yep, I think this means we need an editor, kinda like the sessions
editor. That's a bit more work...

> - "Edit tag ..." --> "Edit tag..."  (get rid of the extra space?)

Easy enough. dfe881200cbb3ee415b59d439eae9888791d4d46

> - Is there a way to do rounded corners on the tags in the Title
> column?  This is a minor wish.

It might be possible, see the last decade of "how do I do rounded tags
in CSS", I don't know how much QT does for this.

> - The tags should ideally be in a somewhat smaller font.

I *think* this is possible.

> - For assigning tags, it would be nice to have a pulldown menu of the
> existing tags, that could be "checked off" to add a tag, or "New
> tag..." to pull up the new tag dialog...I think this would work
> better than the string currently used.

Hmmm... I'll have to think about this a little.

> Overall, I am really looking forward to this feature...I find that I
> want to use it already!

Yep, I'm gonna put it on my calling laptop today or tomorrow, there's
too much good functionality there for me to hold off on.

**Comment by danlyke** [comment] 2018-03-12 17:48
Whoops. Found a possible cause of disappearing tags, fixed that in a5f6a7c082ac4803d521feb4fcc060cc9fb67f32

Re font size: In mainwindow.cpp, SetTagsColorsFromPrefsManager, it's possible to put a "font-size: 10pt;" in that style declaration, but wiring it to deal with zoom is going to be more complicated.

**Comment by danlyke** [comment] 2018-03-12 20:02
`border-radius:` on the `<span ...>` style does not work.

**Comment by mpogue2** [comment] 2018-03-13 03:12
Bug: On Top of Tree (a5f6a7c082ac4803d521feb4fcc060cc9fb67f32), changing the color of tags causes font size to get small.

Feature: I say let's try the 10pt font for tags, and see what it looks like...I can help with zoom (I think!)...

**Comment by mpogue2** [comment] 2018-03-13 04:00
Ah, the 10pt font does not work well at all, because the background color is still the height of the full-size text, so it doesn't look right.  I also tried a bunch of CSS font properties, and most did not do anything.  I was hoping to be able to change the height of the span, but it appears to be fixed.
Small-caps looked nice, but still had the full-height-background-color problem.

I guess let's go with the full-size text for now.  I think once we have the ability to set FG/BG colors for individual tags, this will look pretty good.

Idea: we might want a [X] Show Tags checkbox under View, in case they become too distracting, they can be turned off (but are still searchable?).

**Comment by danlyke** [comment] 2018-03-13 15:30
Still searchable would be a PITA, at least until I can resurrect the
song model notion that I was working on but abandoned because it became
way too complex.

Once we get there... we may be able to do this by creating a much more
complex sub-widget structure within the table: Create a Horizontal
Layout widget, and encapsulate the individual text blocks within that.

**Comment by danlyke** [comment] 2018-03-13 22:48
Duh moment on "still searchable": Could be white on white.

**Comment by mpogue2** [comment] 2018-03-14 02:45
Sorry to say this but....background color for songTable rows alternates in color, and neither color is "white"... :-). OK, so maybe if they are turned off, they aren't searchable.  That seems a small price to pay for having them available when they are needed.

**Comment by danlyke** [comment] 2018-03-17 02:27
Okay  8e704dd713eac10382f9f343e930a0447354abac adds a "Tags" field with submenu off the context menu. We could promote this into the menu itself, but I wasn't sure how that felt with moving the rest of the menu around (it can get pretty large, depending on how you use tags).

**Comment by danlyke** [comment] 2018-03-17 02:46
You can free-form tag with the "Edit Tags..." option, under the Preferences dialog edit tag colors and add or remove tags, and tags are also controllable in the sub-menu from the "Tags  ▶" entry in the context menu.

Known remaining issues (aside from knowing that I've missed something I'm not accounting for right): Haven't figured out how to make 'em invisible but still searchable.

**Comment by mpogue2** [comment] 2018-03-17 02:53
I'm playing with it now!
Bug: In the submenu, there's a blank item at the top.  If you choose it, it attaches a sliver of a tag to that song (presumably a tag with name ""?).  You can unattach it from the song, too.

**Comment by mpogue2** [comment] 2018-03-17 02:55
Hmmm...it went away when I added a tag to one song, but now it's back and I can't get rid of it.
Try adding a tag that is a single space.  Then I think it gets into this weird state...

**Comment by mpogue2** [comment] 2018-03-17 03:00
Bug: when changing tag colors in Preferences, the colors of existing tags don't change when the dialog closes.  

Related? Bug: ensureSchema : QSqlError("1", "Unable to execute statement", "unrecognized token: \"\u0003\"")
ensureSchema : QSqlError("1", "Unable to execute statement", "unrecognized token: \"\u0003\"")
"CREATE TABLE tag_colors (\n  tag TEXT PRIMARY KEY,\n  background TEXT,\n  foreground TEXT,\n  tag_colors tX0\u0003\u0001,\n  songs_songname songs(songname),\n  songs_name_idx songs(name),\n  session_name_idx sessions(name),\n  song_play_song_session_played_idx song_plays(song_rowid,session_rowid,played_on),\n  call_taught_on_dance_program_call_name_session call_taught_on(dance_program, call_name, session_rowid)\n\n)\n"
getTagColors : QSqlError("1", "Unable to execute statement", "no such table: tag_colors")
getTagColors : QSqlError("1", "Unable to execute statement", "no such table: tag_colors")
"SELECT tag,background, foreground FROM tag_colors"

**Comment by mpogue2** [comment] 2018-03-17 03:03
Bug?: In Tag Preferences, there are two small color boxes at the lower left.  I can click on them, but they don't seem to do anything.

Question/bug?: How do I get back to the #RRGGBB notation?  When I change a color, it just colors the whole cell with that color.

Looking pretty good so far...this is exciting!

**Comment by danlyke** [comment] 2018-03-17 18:22
That create schema error is very concerning, because that looks like memory corruption that's occurring very early in the startup process.

The visible #RRGGBB notation is actually a bug, I'm using the exact same code to set the colors after selection as I am on creation, they should just be colors. 

The blank tag thing seems like I need to make my tag split more aggressive, and not let us save blank tags...

Thanks. If you have any leads on the memory corruption issue that'd be awesome, I'll find some time to chase the others.

**Comment by danlyke** [comment] 2018-03-17 20:21
Probably doesn't belong in this feature request, but with the latest master, 99f0df25ff3c33561425012299a8583cd5fc5dcb, I'm getting a pair of `QIODevice::write (QTcpSocket): device not open` warnings when the application first hits the main event loop.

I'll continue on the other stuff and hopefully this'll just go away... (he said, hopefully...)

**Comment by danlyke** [comment] 2018-03-17 21:07
The two boxes on the lower left are supposed to be add and remove a tag. The mismatched slots name was causing that to not work. They're appearing with "+" and "-" in my build, but I may have gotten resource names wrong...

I think I've addressed the last 24 hours of bugs, aside from the memory corruption issue, I'll take a moment to go back and see if I can summarize...

**Comment by danlyke** [comment] 2018-03-17 21:52
> I changed the FG color, and all of the fonts in the Title column went to "tiny". Cmd-0 brought them back to correct size.

I think I need a little more detail to replicate this one.

>   Is there a way to do rounded corners on the tags in the Title column? This is a minor wish.

I think current state is "no, but would be nice"

>   The tags should ideally be in a somewhat smaller font.

This seemed like it'd have to be tied to a better way to render backgrounds, because the rectangles stay the same size.

I think 364e7a53f8e95f0f1149b26f3276397df8a4910f solves your song name color issue. I need a rundown on what's supposed to happen here, because I think there's a really cool feature that I'm not seeing on Linux, if I understand what it's supposed to do correctly.

**Comment by danlyke** [comment] 2018-03-17 22:18
So that leaves us with a view/hide situation... For consistency, I think we don't want to allow tag interactions when tags are hidden.

**Comment by danlyke** [comment] 2018-03-17 22:30
Thinking about this further, because I'm lazy and really don't want to do it, in what situations would someone tag their music library but want to suppress the tag display?

**Comment by mpogue2** [comment] 2018-03-18 04:31
"I changed the FG color, and all of the fonts in the Title column went to "tiny". Cmd-0 brought them back to correct size. -- I think I need a little more detail to replicate this one."
I will replicate and provide more detail.  This was easily reproducible on earlier builds.  I'll check with the latest!

rounded corners: "no, but would be nice" -- yep.  P1 feature, not needed for shipment to Beta.

tags in smaller font: -- yes, I played with this, and could not seem to workaround it.  the BG color is still full-size, even though the font is smaller.  There's probably a way, but it may be more complex.  I think we can put this on the list as a future feature request for now.  This is also a nice-to-have P1 feature -- would not gate shipment to Beta users.

Tag hiding -- why?  Lots of tags becomes visual clutter pretty rapidly, I think, and tags are only needed when we want to search by the tags. So, when we don't actually need to search-by-tag, it's nice to be able to hide them to reduce the clutter.  Similar to being able to turn columns off when not sorting by them, or go to compact mode when those sliders are not needed.  Saves space, reduces clutter, and easily turned back on when needed.  Is this a critical feature?  no.  I would release to Beta without it.  But, it's nice-to-have, I think.  I think that makes it a P1, rather than a P0... :-)

**Comment by mpogue2** [comment] 2018-03-18 04:35
I started up top of tree, and got this when the app came up (font size of Title is small):

![smallfonts](https://user-images.githubusercontent.com/6316003/37562632-e9679152-2a2a-11e8-93a5-3506dd9eb05b.png)

After doing Cmd-0, then Cmd-+ several times, it previously went back to normal, but now in this build it's still small.  Title is always the same size right now.

**Comment by mpogue2** [comment] 2018-03-18 04:36
You can see that the colors are correct for Title now.

**Comment by mpogue2** [comment] 2018-03-18 04:39
Colors of tags are still not persistent, although SOME of them did change to the right new colors, but then they went back to black on green.

**Comment by mpogue2** [comment] 2018-03-18 04:42
+ and - buttons look like this on Mac OS X:

![tagprefs](https://user-images.githubusercontent.com/6316003/37562704-18ba3260-2a2c-11e8-8cc5-5582b8118b3f.png)

**Comment by danlyke** [comment] 2018-03-18 15:01
Aha! And Doh. Fixed the color persistence/table create warning error in 4511a5a9c4665a9554d9dae61c82a62130687223

**Comment by danlyke** [comment] 2018-03-18 15:04
Can you open up preferencesdialog.ui in designer on your platform and copy the appropriate "list-add" and "list-remove" into those buttons? I can't see the difference between those and the session items, even looking directly at the XML.

**Comment by mpogue2** [comment] 2018-03-18 21:23
@danlyke It doesn't look right in Designer, but I'm not sure how to fix it!

Do an all-files search for lock_icon, which works.  Then do an all-files search for list-add, which doesn't.  It looks to me like the iconset needs to be "resources.qrc", but it's currently "list-add".  And, the normalon&off should be "/graphics/lock_icon.png", but it's currently ".".  Same for list-remove.

QAbstractButton in the Designer shows "Theme" = "list-add", maybe that's the "iconset"?  And, the NormalOff = "test123", maybe that's what "." does?  This resources stuff has always been opaque to me...

I'm not quite sure how to fix this, but I suspect that the lock_icon is the model of what we should try....do you see icons on your screen on Linux?  or "+"?  or...?

**Comment by mpogue2** [comment] 2018-03-18 21:40
Bug: header row no longer scales font size as the other items in the songtable change font size

**Comment by mpogue2** [comment] 2018-03-18 21:51
**General comment:**  tags seem pretty usable to me right now!  They are colored nicely with user-selectable colors, they are persistent, when I change the colors, they change in the songTable, they are searchable without having to figure out some separate method to search them.

Nice.

I've gone ahead and merged in the bug fixes I was doing on a branch into master.

**Comment by danlyke** [comment] 2018-03-18 22:00
I see icons on Linux, and I think I copied that over from the sessions editor, which I also see the icons for.

Okay, I've reworked all of those using the XML directly to look like the lock icon. Would you check out 380679e0f5db2d09b98358d4331fa3b589088287 please? Hopefully that has all the icons there.

**Comment by danlyke** [comment] 2018-03-18 22:02
And if that works, I think our outstanding issue with tags is the header row font size (I don't know why that's wrong, but I can probably figure it out) and the font size changing when tags are hidden?

**Comment by mpogue2** [comment] 2018-03-18 22:09
Yes, that worked!  Cool!

Couple of minor UI things:  In the "Edit tags" dialog, I think we would be fine using the filename without .mp3 at the end, rather than the whole path.  Could even just be the Title, rather than the Label - Title.  The dialog would be narrower.  Maybe some help text, too, in a smaller font?  (are they space-separated tags, case sensitive, commas not allowed, or ?).  Maybe an example?

Yep, I think the only major open item is the header font size and the title column font size.  It doesn't happen just when hidden....

**Comment by mpogue2** [comment] 2018-03-18 22:13
I spoke too soon...
Bug:  If I delete a tag using "-" button in the Tag Preferences dialog, it does not remove any of those tags from the songs, and when I come back into the dialog, that tag has not been deleted.  I suspect it should probably remove all of that tag from all songs (otherwise, I have a lot of right-clicking to do to get rid of a tag).

**Comment by mpogue2** [comment] 2018-03-18 22:17
Minor UI suggestion:  could we center the samples in the Sample column in the Tag Preferences tab?

**Comment by mpogue2** [comment] 2018-03-18 22:35
Question: do we still need context menu "Load Song"?
Very minor UX comment: I think we should put a separator after Reveal in Finder, and before the tag stuff, in the context menu, to give it a little visual separation.

I'm into the super minor stuff now... :-)

**Comment by danlyke** [comment] 2018-03-19 02:17
Okay. the "edit tags" dialog is just the stock text entry dialog. I haven't wanted to tackle anything custom for that. I did just use the text edit box.

There's still something I don't understand with song table header font sizes. Sometimes they do what I expect, sometimes they don't. But other than that...

**Comment by mpogue2** [comment] 2018-03-19 04:47
Way cool!  That was super quick!
The headers are still the wrong size on entry to the app, but I think (at least so far) they are consistent with the selected font size at other times.

**Comment by danlyke** [comment] 2018-03-19 17:05
I think if we can move all of the places the font size is set into one function, that'd be a good start. Right now there are more places than I think there should be that there's almost but not quite the same code.

**Comment by mpogue2** [comment] 2018-03-20 17:32
I thought that the font size stuff was all in one place (plus the constructor), but I'll have to check that...I agree that would be a good idea!

Another idea (not critical):  to save people time in setup, I'd love to see a pre-populated list of common tags and colors.  Since the list is editable, people can always change it, but it's hard to get started right now, because you have to know where to look and what to do.  

It may take a couple of weeks for us to come up with a simple list, as we play with it.  My list currently includes: Irish, Halloween, Latin, HOT (as in High Energy), Swing, Bollywood, and DUET.  What's on your list?  We could also ask a couple of callers how they think of it.  Prepopulating with, I dunno, 5 or 10 items, might be very helpful to people trying the program out.

**Comment by mpogue2** [comment] 2018-03-21 03:05
Head font size is fixed by c98c42529ba97f13b8fdcc7cccc0064bb21f7b38 .  I'm not sure why this sort of partially worked before, but it seems to work all the way now.

**Comment by danlyke** [comment] 2018-03-21 15:59
I've seen callers use "nrg" for high energy, but "hot" is fine (though more likely to bring up false positives). "teach" (sparse mellow patter) and "sfgs" are two of mine...

**Comment by danlyke** [comment] 2018-03-21 16:06
And what do you think of "#" as a prefix to search only tags (not sure how to make this discoverable, and it might get in the way), and "-" as a prefix for exclude.

Specifically, "-sfgs" for "gimme only songs I can use 'circle left, AL, partner right, AL, RLG' as my break figure for easy teaching.

**Comment by danlyke** [comment] 2018-03-22 18:10
On the # search, let's use it for a while and see if it's necessary. I
suspect it isn't, though I may add the "-" prefix once I get my music
better tagged.

We might get to the smaller font size eventually, but for right now I'm
not willing to spend too much time pixel tweaking for that. Yes, I'm
lazy, but there are other features I want more!

I can add a little more space easily... wish we had some better way to
do fast turnaround on simple visual tweaks. I realize this is asking a
lot, but if you grabbed a screen shot and moved some of the tags to
where you thought looked right? That'd be useful.

**Comment by mpogue2** [comment] 2018-03-24 04:08
@danlyke I didn't want to change it, without fully understanding all the implications, but I think it  looks pretty good with one extra space:

```
//static QString title_tags_prefix("&nbsp;<span style=\"background-color:%1; color: %2;\"> ");
static QString title_tags_prefix("&nbsp;&nbsp;<span style=\"background-color:%1; color: %2;\"> ");
static QString title_tags_suffix(" </span>");
static QString title_tags_prefix_invisible("<span style=\"display: none;\">");
//static QRegularExpression title_tags_remover("(\\&nbsp\\;)?\\<\\/?span( .*?)?>");
static QRegularExpression title_tags_remover("(\\&nbsp\\;)*\\<\\/?span( .*?)?>");

```

**Comment by phoef** [comment] 2018-03-24 08:14
The Pareto principle (80/20 rule) should also play a role here ;-)
Find this feature already useful.

**Comment by danlyke** [comment] 2018-03-24 15:59
@mpogue2 I think we want to add the extra '&nbsp;' explicitly in the concatenation, because title_tags_prefix is used to wrap each tag.

I'm not keen on adding the "#" ourselves, if someone likes that behavior they can, which maybe is the answer: If you want "#", do it yourself!

On the "-" prefix, I think it's possible to parse this such that it only applies as an exclusion operator if it's precede by whitespace, and not followed by it, but I also think we should probably use it for a while and see how it flows. May not be that important.

**Comment by danlyke** [comment] 2018-03-24 16:06
f6666cd6337da309099b93e11ff4aee2ebf84875 puts an extra nbsp in there. I think it works...

**Comment by danlyke** [comment] 2018-03-30 00:55
Suggestions for better default colors welcomed. And dang it, I accidentally did this in the hotkeys branch, so we'll get it when we merge that.

![tagcolors](https://user-images.githubusercontent.com/88919/38119914-0d906a42-337a-11e8-80bc-fb6aab5f4561.png)

**Comment by mpogue2** [comment] 2018-03-30 04:19
I think the only other one I might add as a default might be Halloween (black on orange, and then change the Bollywood one to something else?).   The only one I would delete would be "sfgs", because it wasn't at all obvious how to decode that (I don't think other callers would understand that tag either -- this must have a special meaning for you! :-).

**Comment by mpogue2** [comment] 2018-03-30 04:20
Also, we could rebase the tags changes onto Master -- they are quite useful, they are low risk, and probably don't overlap with any of the hotkeys changes (right?)...

**Comment by danlyke** [comment] 2018-03-30 20:37
Okay, e43c5e8f0b662df34b064ea038557cc43bf5e229 I've moved the changes over into Master (didn't do a rebase, I'll just sort the merge issues when we get there), added Halloween, changed the Bollywood colors a bit, and removed "sfgs".

though I'm tellin' ya, if we had a way to track it I'm betting "sfgs" will be the most used and usable singing call tag.

**Comment by danlyke** [comment] 2018-05-23 21:16
So is everyone happy with the tags? I'm gonna close this, feel free to re-open with comments if there's something additional (or create a new issue).

**Closed by danlyke** 2018-05-23 21:16 UTC
Labels: enhancement

**Comment by mpogue2** [comment] 2018-05-24 02:00
Happy, yes!

**Comment by danlyke** [comment] 2018-06-05 22:36
Hey, what would you think about changing the current "Title (type to search)" to "Title (type to search, prefix words with '-' to exclude, '#' to search only tags)" or something similar to help discoverability...

**Comment by mpogue2** [comment] 2018-06-06 02:11
I am inclined to put it in a tooltip, rather than expanding the current text....

**Comment by danlyke** [comment] 2018-06-06 14:15
Sounds good. I'll add something appropriate to the 3 fields.
