### ISSUE TITLE
Bug: changes to pitch and tempo forgotten when playlist is loaded

### ISSUE THREAD

**Issue by mhkull** [mpogue2/SquareDesk#42] opened 2017-04-12 16:30 UTC

**Comment by mpogue2** [comment] 2017-04-15 04:04
This behavior was intended:  CSV playlists save their tempo and pitch settings inside the playlist file, and they are restored when the playlist is loaded again.  M3U playlists do not.  That way, you can pre-setup a "Tuesday night" playlist, with the pitch/tempo settings preset to what your Tuesday night group needs.

Do you think it should not save/restore the pitch/tempo settings?  I'm open to changing this behavior, depending on what the consensus is.

**Comment by mhkull** [comment] 2017-04-16 10:38
Here is how I think of a playlist. A playlist is a selection of music form my main playlist (the master playlist, so to speak). I do use the master playlist as well as the smaller list for the special occasion tailored to the needs of the event. Until your question I did not think of the smaller playlist as not just a selection, but a selection tailored to the special event. I really like this idea! Keep it up. However pitch and tempo settings to the master list should be saved as well.

Maybe I need to describe my observation a little deeper: I made changes to the master list, then loaded a saved playlist and realized ALL changes made from starting the program to openeing the saved playlist were lost. Does that help?

**Comment by mpogue2** [comment] 2017-04-16 22:10
Yes, I think I understand.  You consider the changes made to items in the Master List (what we call the Song Table) to be persistent changes.  Then, when you save a Playlist, you expect it to be a snapshot of the current settings for those songs as well as the songs themselves.  Is that right?

If so, here is the sequence to reproduce this:
1) open app
2) load a song by double clicking, let's say  its pitch and tempo are currently P+1, T110%.
3) change its pitch and tempo to zero (P0, T100%)
4) Add that song to a Playlist (as #1), and save the playlist (song = P0, T100%)
5) Change the pitch and tempo, say to P-2, T90%
6) Load the Playlist from step 4 above.  We see P0, T100%.
7) Close the app and reopen it.
8) Load that song by double clicking.  
      You expect: P-2, T90%
      Current behavior: P0, T100%.

Did I get that right?

**Comment by mpogue2** [comment] 2017-04-30 04:40
I think this one is fixed by the fix for #40.  Changes to the master playlist, if you will, are persistent now.  CSV files will save Tempo/Pitch, while M3U files will not.

**Closed by mpogue2** 2017-04-30 04:40 UTC
Labels: question
