### ISSUE TITLE
Feature: Speed of auto-scroll cuesheet

### ISSUE THREAD

**Issue by mhkull** [mpogue2/SquareDesk#39] opened 2017-04-11 12:30 UTC
Speed of auto-scroll cuesheet should be variable and saved to the file individually

**Comment by danlyke** [comment] 2017-04-11 20:59
Talk to me a little more about the specifics of the use case here. Is this for a cuesheet that has multiple sets of calls in it (ie: Mainstream at the top, Advanced at the bottom), or the calls at the top and the lyrics further down, or...?

The problem is that we're currently scrolling through the cuesheet based on how far through the song the playback is. It's an absolute relationship. So we could do a "how fast and where do we start" sort of scroll, or we could try to figure out how fast to scroll based on the total length of the cuesheet and where the cuesheet scroll started and save those two settings, but I'm trying to figure out an elegant solution.

**Comment by mhkull** [comment] 2017-04-12 07:06
I like your fist idea - however that was not my intention.
I thought it would be a smart thing to have some kind of landing marks within the cuesheet, so when the music enters the middle break (or a second before) the cue sheet will jump to the right place. That could be the case with all parts of a singing call: Start Music - Jump to Opener, Music enters Figure 1 - Cue Sheet Jump to Figure 1, Music enters Figure 2 - Cue Sheet Jump to Figure 2 or remain with Figure 1 - Music enters Middle Break - Cue Sheet jump to middle break - ....

My original thought was to add a field to the preferences that influences the speed of the scroll.
But when user edit the cue sheets that value might be different with every cuesheet.

A smart solution ist better, indeed. So the length of the cuesheet in relation to the lenght of the music should get the scroll value.

I believe that in order to get more people interested in square dance, the cue sheet plays a vital part. Coming from the age of records, it was a no go to read from the cuesheet. Today with all the info at your fingertips it may be ok to read from the screen, but the information given there must be in its best form.

**Comment by danlyke** [comment] 2017-04-12 17:12
Smarter cue sheets is definitely on my list. Including things like the ability to choose and sub in figures... Right now I call with the lyrics on the laptop and the figures I'm using in a separate book, and it'd be nice to combine those...

The current scroll chooses the place in the cue sheet based on the song play position. I think that the right way to handle more detail than this may be to allow multiple cue sheets so that you can have separate cue sheets with the Opener/Break/Closer for your Advanced tips vs your Mainstream tips, and use your own figure.

At least until we can sub in different figures...

**Comment by mpogue2** [comment] 2017-04-15 03:53
There is talk at Callerlab of standardizing cue sheets.  I am definitely in favor of this.  Also, I'm talking to other caller-programmers about encoding the calls as well, to allow for better interoperability between programs.  Thirdly, MP3 has a concept of "synchronized lyrics", and eventually I'd like to add that back into the lyrics format (but it's a more complex feature).  An earlier version of SquareDeskPlayer was focused on lyric editing, both Unsynchronized and Synchronized Lyrics.  So, the format already exists for this, if we want to leverage this.  (And taglib also supports accessing them.)

**Comment by mpogue2** [comment] 2019-07-01 01:17
Closing this one, since we have auto-positioning of the cuesheet based on the song play position, and it works pretty darn well!

**Closed by mpogue2** 2019-07-01 01:17 UTC
Labels: enhancement
