### ISSUE TITLE
Bug: Right click under playlists crashes SquareDesk

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#1003] opened 2023-12-27 05:53 UTC
With the latest version as of 27 Dec 2023, if I right click in the area beneath Playlists it crashes; traceback attached.
In case it's relevant, the pictures on the wiji (which is great!) have tree playlists  -- I don't have them (haven't figured out what they are).
[traceback.txt](https://github.com/mpogue2/SquareDesk/files/13775851/traceback.txt)

**Comment by mpogue2** [comment] 2023-12-27 08:58
Thanks for the report!  I reproduced the problem here.  
The problem is that if you're not pointing at a real item in the treeWidget when you click, it crashes.  I should be able to fix that, but I just broke the build when I updated Xcode yesterday, and I have to fix that first... :-)

**PLAYLIST FOLDERS**
If you go in to your playlist folder (inside Music Folder), and make sub folders there, you can organize your playlists hierarchically.  Click on the disclosure triangles to open up each folder and see the ones inside.

I have lots of playlists (like more than 100), so I now do something like this:

- Playlists
- - Jokers
- - - 2022
- - - - Jokers_2022.01.05
- - - - etc.
- - - 2023
- - - - Jokers_2023.11.12
- - - - Jokers_2023.11.19
- - - - etc.

**Comment by mpogue2** [comment] 2023-12-30 03:45
Fixed by: d9ff27b650710c0d5a118eaf2ca823a6cc724a98

I was dereferencing a null pointer, when there was no tree widget item under the cursor at the time of the right-click.
Now I just return, if that happens.

**Closed** 2023-12-30 03:45 UTC
Labels: bug

**Comment by mpogue2** [comment] 2023-12-30 03:54
Oh yeah, and don't leak any memory when we return.  Commit: 3422d61dea63e003b86c5646700a995ade0a500d

If right-click in treeWidget, and there's nothing underneath the cursor, we return early, BUT we need to not leak the twMenu memory.  Changed so we don't allocate it, if we return early.
