### ISSUE TITLE
Music dropouts when using a USB volume knob

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#866] opened 2023-05-25 14:12 UTC
Square Desk 1.0.4 
I am using a USB volume knob on my MacBook (Intel). When the knob is turned the music has dropouts / it stops playing while the knob is turned. The MacBook is running without power connection so energy saving mode might be part of the problem. The dropouts get worse when the music is transferred via Bluetooth.
The knob itself is a piece of hardware that is USB connected and simulates a keyboard.

**Comment by Gero5** [comment] 2023-05-26 14:38
I tried other music players in comparison. All except Square Desk are working well and the music volume is adjusted with no stops or dropouts. To me it seems to be another performance issue as the music slightly slows down a bit before it turns quiet completely.

**Comment by danlyke** [comment] 2023-05-26 14:54
interesting. I haven't had a chance to re-dive into that code, but that
suggests that maybe we're processing too large a chunk at a whack on a
volume change?

**Comment by Gero5** [comment] 2023-05-26 15:19
> maybe we're processing too large a chunk at a whack on a volume change?
the fact that the information 'volume change' is transferred via USB port must have some influence as well. When I change the volume on the Touch Bar the Square Desk music player works as it should - even on radical volume changes.

**Comment by danlyke** [comment] 2023-05-26 17:01
Yeah, I was thinking that maybe that particular USB device is super noisy
in its request for volume changes. I'll have to acquaint myself with the
code, but I doubt it's the USB factor alone, otherwise changing volume via
the keys on a USB keyboard, or with the mouse, would be too much.

**Comment by mpogue2** [comment] 2023-05-26 21:51
Without your USB knob, but with a test setup that is otherwise mostly comparable, I could not duplicate the problem here

**My test setup:**
- MacBook Pro 13" 2017 (5 yr old X86)
- Bug Sur 11.7.5
- SquareDesk 1.0.4X (X86 version)
- Running on battery (full charge, NOT CPU limited with low battery condition)
- System audio output to a Bose WC35 Bluetooth headphone.

**Tests (while playing an MP3 song in Squaredesk):**
1. I moved the System volume up and down rapidly, no dropouts.
2. I moved the SquareDesk volume slider up and down rapidly, no dropouts.
3. I moved other controls (like Bass) up and down rapidly, no dropouts.

In all of the above test cases, CPU consumption according to Activity Monitor goes to 100%, but still no dropouts.

My conclusion is that it's probably your USB volume knob that is somehow causing the problem, perhaps because of the software driver used to connect the knob to System Volume?  Or, maybe that in combination with being in Low Battery Mode (which I was not -- my battery was fully charged, although the battery monitor has been nagging me that my battery really should be replaced!).

If you could, please post the model number of your USB knob, and the results of testing similar to the above tests while watching Activity Monitor.  I don't think there's much more we can do without owning one of the exact USB knobs that you have.

P.S. I also tested on an M1 MacBook Air, and no dropouts either, but this is on a higher end MacBook than the one you are using....

**Comment by Gero5** [comment] 2023-05-26 21:53
Accidentally I have three different volume knobs on my desk a the moment. They work fine with other music players like Apple Music, QuickTime Player, VLC, Spotify, Zoom. Only Squaredesk (sigh!) seems to be too sensitive to what they send. Chances are high though that all three volume knob device use the same chip and method to simulate keyboard strokes. I think that Square Desk is _hyperactive_ in reacting to the events triggered by the usb devices.
Anyway if anybody can give me a clue how to sniff the usb protocol on a Mac I can log what the knobs are sending - if that helps.

**Comment by mpogue2** [comment] 2023-05-26 22:04
Could you kindly list the model numbers of the three volume knobs, and the MacBook model that you are using?  Does the problem go away when you are running on wall power instead of battery?  What happens to Activity Monitor when you are changing volume?

Note: If they are all just sending keystrokes, they are probably only changing system volume, not SquareDesk volume.  If this is the case, SquareDesk is not changing what it is doing at all -- it is literally taking a constant amount of CPU time.  The system, however, may be taking up more CPU time though, which could starve SquareDesk.

That would probably be helped by commit d2a02c03d8d345ac8ae1b5349a72ffe87e9dc243, which we did as part of #810, but will also help in similar CPU starvation cases.  This commit is NOT in v1.0.4X, but will be in the next release (likely 1.0.5).

**Comment by mpogue2** [comment] 2023-05-26 22:15
Also, I don't think we need you to sniff the USB protocol.  The USB part of the CPU time is very very tiny.  What is a lot bigger part of the CPU time is rapidly changing system volume (even when SquareDesk is not running).

Here are some actual measurements on the same system I listed above (running on battery, with BT output):

While playing an MP3 song in SquareDesk, these are the CPU times in percent:

```
        NO VOL CHANGES       RAPID VOL CHANGES
System      5                   30
User       15                   45
------------------------------------
Idle       80                   25
```

**Comment by Gero5** [comment] 2023-05-26 22:19
volume knobs:
- https://www.amazon.de/dp/B0B82LKLCY
- https://www.amazon.de/dp/B07Z3DH5PV
- https://www.amazon.de/gp/product/B07PQ52NZL

Mac Book Pro 13", 2017, 3,1 GHz Dual Core Intel i5, 8 GB, Ventura 13.4

**Comment by mpogue2** [comment] 2023-05-26 22:32
1. Vaydeer 2022
2. Cooidea
3. Aimos

I had no idea there were so many of these volume controls available!

My system is mostly similar: 
Mac Book Pro 13", 2017, 3.1 GHz Dual Core Intel i5, 16 GB, Big Sur 11.7.5

I'm wondering if you have other stuff on your MacBook that I don't, that listens to system volume control events.  The Activity Monitor data should be able to tell us that.  I doubt that the memory difference (8 vs 16GB) makes any real difference here.

**Comment by Gero5** [comment] 2023-05-26 22:38
system and user CPU usage  when I play a same song with QuickTime and use the volume button:
System 36
user 37
music ist constantly playing

Square Desk and the volume button:
System 44
User 48
music slows down, dropouts

**Comment by mpogue2** [comment] 2023-05-26 22:39
What do you see for CPU times when you are NOT changing the volume rapidly?

**Comment by Gero5** [comment] 2023-05-26 22:44
when you are NOT changing the volume rapidly
system around 1 - 3 
user 3 - 6

**Comment by Gero5** [comment] 2023-05-26 22:56
When I do the same rapid volume changes using the Touch Bar the system/user percentage is at the same level but the music does **not** slow down and has **no** dropouts.
...?

**Comment by mpogue2** [comment] 2023-05-26 23:08
Ah, I should have also specified that in my test reporting above.  When I was rapidly changing the volume on X86 Macbook, I was indeed using the Touch Bar to do so, because it generates the most system volume change events (way more than I could generate with the keyboard alone).

So, it does seem to be specific to your USB devices, which probably all use the same method for volume changing.
You are about 14% higher System CPU usage (changing volume via USB known) than I am (changing volume via Touch Bar).  I suspect you might see the same.

If that hypothesis holds, the root cause might be that the USB knobs all use 15% more CPU time (15% of an entire 3.1GHz CPU!), and that starves SquareDesk. If that's the case, the next test will be to have you try SquareDesk 1.0.5 when it comes out, which will have the bumped-up priority for the sound thread.  That eliminated the previous problems we saw with the screensaver, and my guess is that it will have a positive effect here as well.

**Comment by Gero5** [comment] 2023-05-26 23:19
>Vaydeer 2022
Cooidea
Aimos
I had no idea there were so many of these volume controls available!

the name may change in a few days. these are arbitrarily exchangeable china brands.
you find the same devices on aliexpress with other brands printed on
https://aliexpress.com/item/1005003261903176.html

**Comment by Gero5** [comment] 2023-05-26 23:30
> the root cause might be that the USB knobs all use 15% more CPU time

No. The numbers (system/user percentage) are identical on my system. but wie are at the limit here 44+48 = 92 % cpu usage. 
still the behavior is very different. with the Touch Bar the music does not slow down and has no dropouts.
with the usb device the music slows down and has dropouts.

**Comment by mpogue2** [comment] 2023-05-26 23:50
Unless I am not fully understanding your numbers, I think they are 15% higher with the USB knob than mine are with the Touch Bar.  You're at 92% total, and I am at 75% total.  I don't have a USB knob to try here, unfortunately, to try to duplicate what you're seeing.  Since the knob appears to change System volume, that has nothing to do with SquareDesk (other than taking CPU time away from the audio thread in SquareDesk, I think).

Based on what we know so far, I think the best approach for your USB knob setup will be to have you try a newer version of SquareDesk that sets the thread priority much higher for music playback.

**Comment by Gero5** [comment] 2023-05-29 12:01
v 1.0.5 ist solid as a rock with all my funny USB devices. Even with the wildest turns: No music slowing down, no dropouts. Nice.

Still Square Desk is consuming about 10 % CPU when doing nothing(!), which seems to be a lot to me.  20 % when playing music. I do not know how much or if any performance optimization is already implemented in this version besides the thread priority for the music player?

**Comment by mpogue2** [comment] 2023-05-30 02:32
Glad to hear that it solved the dropout problem for you!  I'll close this ticket now.
While there are some minor optimizations for startup time, there are no other CPU utilization changes in the 1.0.5 release -- #799 will be used to continue to track that.

**Closed by mpogue2** 2023-05-30 02:32 UTC
