### ISSUE TITLE
bug: new Playlist '607 audio files found' is not saved when quitting SquareDesk

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#913] opened 2023-08-05 21:19 UTC
use case:
- Clear playlist
- Add one item to (new) playlist
- Quit SquareDesk
- SquareDesk creates the following message with a bit strange name for a new playlist
<img width="418" alt="Bildschirmfoto 2023-08-05 um 23 00 06" src="https://github.com/mpogue2/SquareDesk/assets/128936259/1fbb3328-35a2-4c42-80bb-251877ebada0">

- when I klick 'Save' SquareDesk quits, but no playlist is saved

Sometimes the message says "Playlist 'untitled' has been modified" - then everything works as expected. SquareDesk asks for a name and folder and saves it. I cannot tell why and when it takes the system message as title for the playlist.

**Comment by mpogue2** [comment] 2023-08-06 22:45
This is a good bug!  Thanks for reporting it!  

It is doing that because in cases where a playlist is already loaded, the playlist and its modified-or-not status is in the status message.  However, looking at the status message for the name of the playlist is NOT correct when the playlist is new and has not been saved/named yet.

Nice catch!

**Comment by mpogue2** [comment] 2023-08-07 07:00
Commit: 5a485045e216bc03d048f098792a757dfecb0d9b

Sometimes came out as "Playlist '607 audio files found' has been modified.  Do you want to save your changes?"  This is now fixed, so that the correct "Untitled" is the default name.  I checked multiple quit use cases, so I think this is fixed now.

Root cause was that I was using the status line to hold the playlist name, when there was already a variable designed to do just that.  So, when the status line had status instead of the playlist name (like in this use case), hilarity ensued.

**Comment by mpogue2** [comment] 2023-10-16 02:04
I believe this is fixed, so closing.

**Closed by mpogue2** 2023-10-16 02:04 UTC
Labels: bug, Ready for final check
