### ISSUE TITLE
Help Dan get the generic Mac build ironed out

### ISSUE THREAD

**Issue by danlyke-meshos** [mpogue2/SquareDesk#396] opened 2018-08-20 21:37 UTC
Commit c13f22e6d0b9217d99d200c07c6c6f15acba48e2 should make all of the /Users/mpogue/... hardcoded paths build relative for the Mac, and it looks like I've got a complete build, but I get a "SquareDesk cannot be opened because of a problem" error dialog that says (in part):

```Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: libquazip.1.dylib
  Referenced from: /Users/USER/*/SquareDesk.app/Contents/MacOS/SquareDesk
  Reason: image not found
```

The file appears to be there:

```$ find SquareDesk.app -name libquazip.1.dylib
SquareDesk.app/Contents/MacOS/libquazip.1.dylib```

It looks like it's the same size as the file that  ../qazip/libquazip.1dylib symlinks to, ../quazip/quazip/libquazip.1.0.0.dylib. I'm guessing there's some further dependency which is getting lost, but I haven't figured that out yet.

**Comment by mpogue2** [comment] 2018-08-25 02:37
@danlyke To run the Mac OS X version outside of the QtCreator context, you need to run the Packageit.command file, located in the test123 folder.  It will modify the libraries so that they can be loaded from inside the Mac app bundle, even when you move the bundle around.

To check this after running the Packageit command file, try double-clicking on the version of the app that is built in ./Install, inside the build-SquareDesk-Desktop_Qt_5_9_3_clang_64-bit-Release folder.  That version should work.  If it does not, it will show you a stack trace that should suggest what the problem is.

**Comment by mpogue2** [comment] 2018-10-20 23:40
@danlyke did you get this figured out?

**Comment by danlyke** [comment] 2018-10-21 01:45
Not yet. I haven't got the tuits to get back around there, but I did
figure out that you're doing the build from the Qt tool and not from
the command-line as installed from Homebrew, so I suspect that next
time I try it it'll work, if I can figure out what thing to open from
the Mac Qt GUI thing.

**Comment by mpogue2** [comment] 2018-10-21 01:49
Yes, I build the final version in the Release mode from Qt, then I run the PackageIt.command script to fix the library pointers, and package everything together.  PackageIt.command needs to be modified each time for the version number, but it otherwise works.

Similar for Windows.  I always build in Qt in Release mode, then there is a copy script to copy everything to a release directory, and then there is an installer script to build the installer.

**Comment by mpogue2** [comment] 2023-01-01 07:04
@sharmanr has this building, so closing this one.  I believe you can pull down the source, run QMake, Cmd-R to run, and it should all work on Mac OS build.

**Comment by sharmanr** [comment] 2023-01-01 20:08
>  I believe you can pull down the source, run QMake, Cmd-R to run, and it should all work on Mac OS build.
> 

Well,  sort of…

I pulled down the source, followed instructions in test123/README.txt to do the make of soundtouch then opening the project.  I think the README file should clarify which project file to open,  it’s SquareDesk.pro not test123/test123.pro (which gives confusing errors!!!).

You seem to need to “configure” the project;  I went with the default Desktop (arm-darwin-generic-mach_o-64bit).

Using Command-B to build produced 2 errors:
Project ERROR: Could not resolve SDK SDKVersion for 'macos13.1' using --show-sdk-version
Error while parsing file /Users/richard/src/SquareDesk-master/SquareDesk-Dev/test123/test123.pro. Giving up.

To find what sdk version I had I ran ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
which showed: 
MacOSX.sdk	MacOSX13.0.sdk	MacOSX13.sdk

So I changed the line in test123/test123.pro
from
    QMAKE_MAC_SDK = macosx13.1
to
    QMAKE_MAC_SDK = macosx13.0

and tried again.  It went further this time, then died with these errors:

mkdir: /Users/richard/src/SquareDesk-master/build-SquareDesk-Desktop_arm_darwin_generic_mach_o_64bit-Debug/test123/SquareDesk.app/Contents/soundfx: File exists

From instructions in test123.pro I deleted the MacOS directory:

% rm -fr /Users/richard/src/SquareDesk-master/build-SquareDesk-Desktop_arm_darwin_generic_mach_o_64bit-Debug/test123/SquareDesk.app/Contents/MacOS

but that didn’t fix it:

mkdir: /Users/richard/src/SquareDesk-master/build-SquareDesk-Desktop_arm_darwin_generic_mach_o_64bit-Debug/test123/SquareDesk.app/Contents/soundfx: File exists

In test123.pro I tried cheating, by changing $(MKDIR) to $(MKDIR) -p  but that just made it fail on the next statement 

cp -f -R /Users/richard/src/SquareDesk-master/SquareDesk-DEV/test123/soundfx/2.clown_honk.mp3 /Users/richard/src/SquareDesk-master/build-SquareDesk-Desktop_arm_darwin_generic_mach_o_64bit-Debug/test123/SquareDesk.app/Contents/soundfx
mkdir: /Users/richard/src/SquareDesk-master/build-SquareDesk-Desktop_arm_darwin_generic_mach_o_64bit-Debug/test123/SquareDesk.app/Contents/soundfx: File exists


So then I deleted the whole build directory

***@***.*** SquareDesk-master % rm -fr build-SquareDesk-Desktop_arm_darwin_generic_mach_o_64bit-Debug

and then it worked.   I tried making a dummy change to a cpp file and did a build expecting the same problem but it worked fine.

**Comment by mpogue2** [comment] 2023-01-01 23:04
@sharmanr Updated the README.txt file as per your suggestions.  Could you kindly read it over, and see if I did it right?

**Comment by sharmanr** [comment] 2023-01-01 23:27
That looks good,  thanks.

**Comment by mpogue2** [comment] 2023-01-02 00:06
Thank you, @sharmanr !

**Closed by mpogue2** 2023-01-02 00:06 UTC
