### ISSUE TITLE
Bug: If there exists patter and singer with same name, patter always pulls up singer cuesheet

### ISSUE THREAD

**Issue by pkbott** [mpogue2/SquareDesk#1122] opened 2024-06-10 23:40 UTC
When I choose a patter song and then go to the lyrics tab, there is a singing calls lyrics there when there should be a template.  How do I get it to default to the template?  Is there a file I need to amend to do this?

**Comment by mpogue2** [comment] 2024-06-11 00:40
This is a new feature (we call it "peek"), but let me be sure that what you're seeing was what we intended, and not a bug in our implementation!

How we expect it should work now:
- If a patter song is loaded from a playlist, and there is a singing call in the very next row of that same playlist, that singing call's cuesheet will be loaded (instead of the patter template).  Then, while calling the patter portion of the tip, the caller can toggle over to the cuesheet, and see the figure that will be used there.  The caller can then run through the singing call figure in the patter (a pretty typical thing to do, I do it almost every tip), so that the dancers are familiar with it by the time the singing call comes around.
- Prior to a cuesheet (any cuesheet) being loaded into the Cuesheet Tab, loading a patter from the main song table (not a playlist) will indeed load the patter template. But, once a cuesheet is loaded into the lyrics tab, it won't be evicted by the patter template when a patter is loaded (from either main song table or a playlist).

I think it's a fair question as to "how do I get to a template now?"  Right now I think the answer is "when you first start SquareDesk, and before loading any singing calls in SquareDesk, load a patter from the main song table".

I think we have an open Issue to improve this, for example, by always listing the templates (anything matching *.template.html, allowing you to make a set of templates if you want to) in the dropdown menu on the Cuesheet Tab.  Then, you'll always have access to the templates, through a somewhat different mechanism...maybe something like this would work for you?  Our thinking is that callers will want multi-column templates in addition to single-column templates, for example, and this might allow that.

@sharmanr, did I explain this correctly?

**Comment by mpogue2** [comment] 2024-06-11 01:04
OK, if you are NOT using playlists in your testing, it should NOT have switched over to the cuesheet tab when you hit play.

Were you in Light Mode or Dark Mode when this happened?  I need to try to replicate this problem, because it's likely a bug.

**Comment by mpogue2** [comment] 2024-06-11 01:09
I could use a screenshot for this problem too, when. you get a chance.  

I'm wondering if your songs are organized in such a way that the program can't tell that the song is NOT a singing call.  Only singing calls should switch over to the cuesheet at first playback.  

I've tried to duplicate the problem here, and so far I can't get it to switch to the cuesheet tab, if it's not a singing call that is loaded.

**Comment by pkbott** [comment] 2024-06-11 01:26
How do I do multiple column lyrics pages?  I like that ideaReady to try something FUN, UNIQUE and ***@***.*** Square Dance Group:  https://www.facebook.com/groups/squaredanceforfun/On Jun 10, 2024, at 8:40 PM, Mike Pogue ***@***.***> wrote:﻿
This is a new feature (we call it "peek"), but let me be sure that what you're seeing was what we intended, and not a bug in our implementation!
How we expect it should work now:

If a patter song is loaded from a playlist, and there is a singing call in the very next row of that same playlist, that singing call's cuesheet will be loaded (instead of the patter template).  Then, while calling the patter portion of the tip, the caller can toggle over to the cuesheet, and see the figure that will be used there.  The caller can then run through the singing call figure in the patter (a pretty typical thing to do, I do it almost every tip), so that the dancers are familiar with it by the time the singing call comes around.
Prior to a cuesheet (any cuesheet) being loaded into the Cuesheet Tab, loading a patter from the main song table (not a playlist) will indeed load the patter template. But, once a cuesheet is loaded into the lyrics tab, it won't be evicted by the patter template when a patter is loaded (from either main song table or a playlist).

I think it's a fair question as to "how do I get to a template now?"  Right now I think the answer is "when you first start SquareDesk, and before loading any singing calls in SquareDesk, load a patter from the main song table".
I think we have an open Issue to improve this, for example, by always listing the templates (anything matching *.template.html, allowing you to make a set of templates if you want to) in the dropdown menu on the Cuesheet Tab.  Then, you'll always have access to the templates, through a somewhat different mechanism...maybe something like this would work for you?  Our thinking is that callers will want multi-column templates in addition to single-column templates, for example, and this might allow that.
@sharmanr, did I explain this correctly?

**Comment by mpogue2** [comment] 2024-06-11 01:51
Here's a sample file (below).  This is really a template, but there's no good way to stick in multiple templates right now.

So, the best way right now to try it is this:
- copy the file below to your lyrics folder, and rename it to "label - song name.html" (whatever your song is)
- restart SquareDesk, and load that song
- go to the cuesheet tab, and pull down the menu to view the new lyrics
- edit the template with the lyrics from your song (yeah, this is painful, I know)

The second best way to try it is:
- edit the html cuesheet for your song in a text editor, and make the changes suggested in #728 by hand.

Here the test file (I can't post the file here directly, you'll have to unzip this one to uncompress it after downloading):

[4B 6085 - Happy Trails.2col.html.zip](https://github.com/user-attachments/files/15781014/4B.6085.-.Happy.Trails.2col.html.zip)

**Comment by pkbott** [comment] 2024-06-11 02:23
So the patter record was California Dreaming and the lyrics tab chose the California Dreaming singing call which was understandable for a choice.  I can't get rid of that page of lyrics either.  If there was a  template choice at the top of EVERY one of them that should fix this issue with picking the wrong cue sheet?
<img width="1440" alt="Screenshot 2024-06-10 at 10 17 53 PM" src="https://github.com/mpogue2/SquareDesk/assets/55835882/236248b3-1bb5-4ae7-b7a7-f031daa6f9ad">

**Comment by pkbott** [comment] 2024-06-11 02:31
> I could use a screenshot for this problem too, when. you get a chance.
> 
> I'm wondering if your songs are organized in such a way that the program can't tell that the song is NOT a singing call. Only singing calls should switch over to the cuesheet at first playback.
> 
> I've tried to duplicate the problem here, and so far I can't get it to switch to the cuesheet tab, if it's not a singing call that is loaded.

So the issue for me at least is only for music that is also a singing call.  I have turned off the auto switch over to cue sheet is all and I'll be fine.

**Comment by mpogue2** [comment] 2024-06-11 02:36
Ah, this is a scenario we have not encountered before!  It sounds like the problem is related to the fact that you have a patter recording and a singing call recording with the same name....

Yeah, I bet it thinks in this case that pulling up the singing call cuesheet is the right thing to do.  How would it know otherwise? :-)

I'll have to think about this scenario.  Maybe there's a way to make it do something more reasonable.  Off the top of my head, I can't think of anything yet... :-)

BTW, thanks SO much for reporting these!  It's super helpful to get this kind of detail!

**Comment by pkbott** [comment] 2024-06-11 03:23
Maybe if it’s category is patter it pulls template file?

[image: IMG_0462.PNG]
*Ready to try something FUN, UNIQUE and DIFFERENT?*

*Website:*  https://callerpaul.com
*Email:*  ***@***.***
*FaceBook Square Dance Group:  *
https://www.facebook.com/groups/squaredanceforfun/

**Comment by pkbott** [comment] 2024-06-11 03:25
I do use some patters as both patters and singing calls as do others. No
problem just seeing more of the program as I get back in the swing of
things.

[image: IMG_0462.PNG]
*Ready to try something FUN, UNIQUE and DIFFERENT?*

*Website:*  https://callerpaul.com
*Email:*  ***@***.***
*FaceBook Square Dance Group:  *
https://www.facebook.com/groups/squaredanceforfun/

**Comment by mpogue2** [comment] 2024-06-11 04:28
I am working on something that I think is better (at least for now).
Hang on until I can get it working...almost there.

**Comment by mpogue2** [comment] 2024-06-11 08:53
Ah, this is more complex than I expected.

**Comment by sharmanr** [comment] 2024-06-11 17:19
The explanation is correct except that if it finds a cuesheet for a patter it will use that,  then (the rest of your explanation)

**Comment by pkbott** [comment] 2024-07-31 15:04
I think that the ability to choose a template file here solves this issue.

**Comment by mpogue2** [comment] 2024-08-01 20:11
Verified, so closing.

**Closed by mpogue2** 2024-08-01 20:11 UTC
Labels: bug
