### ISSUE TITLE
Entering resolve in sd confuses SquareDesk

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#774] opened 2023-03-13 23:30 UTC
I found sd had a resolve command so tried out entering a few commands:  Square Thru 4;  Veer Left;  Couples Circulate;  Bend The Line.  All was well.
<img width="347" alt="ss1" src="https://user-images.githubusercontent.com/76225465/224854324-ef063c4b-b9fc-4c1e-8710-bfa40a59a23f.png">

I then typed resolve.  It came with "Circ, AL, ½ prom" which is interesting 
<img width="341" alt="ss2" src="https://user-images.githubusercontent.com/76225465/224854344-82ad5974-da8a-42d1-ab77-e5db270edb43.png">

but after that if I hit F11 or F12 I see only blank lines, the sequences have disappeared.
<img width="336" alt="ss3" src="https://user-images.githubusercontent.com/76225465/224854365-9addac5d-042b-48c5-8b34-0ab0edd65e94.png">
Switching to Music or Lyrics tab then back to SD doesn't clear the. problem.

**Comment by mpogue2** [comment] 2023-03-14 07:08
Could you post the commit # that you're testing?  I think you're on an older version, if F11/F12 can do this...

The root cause of the resolve problem is that we haven't implemented support for listing resolves yet (AFAIK)... :-)

**Comment by sharmanr** [comment] 2023-03-14 07:31
Hi.  I have a new Mac mini (m2) as my desktop.  Nice hardware, shame about the software!   Really flakey.   Right now I can’t read mail on it (it suddenly stopped working!)
but I can “screen share” into my M1 laptop. 

Anyway, to answer your question, I have done a git pull to your latest version; GitKraken shows I have #752: allow function key reassignment by file naming convention. However, when I wrote the email this afternoon mentioning  about F10 and F11 I was running several versions earlier.  I think just after “add Time-in-tip display”; if not it would have been the “ignore comments of call colouring” update.

Right now SquareDesk is unresponsive within SD.  I press F3 for example and nothing happens.  I’m able to attach wit QtCreator rejects the value of key which is 16777267 at line 3307
    if (inSDEditMode && key != Qt::Key_Up && key != Qt::Key_Down) {
//        qDebug() << "Ignoring key: " << key << modifiers;
        return(true);
    }

Whether this is a bug in SquareDesk or the rotten software running on this machine I don’t know!  (I have the same os version on this laptop;  for some reason it works reasonably well there!).

Time for a reboot.

Richard

**Comment by sharmanr** [comment] 2023-03-14 07:39
I'll try and look at this tomorrow and get back to you.  Right now this wretched machine is causing too much trouble.

----- Original Message -----

**Comment by sharmanr** [comment] 2023-03-14 16:39
Ok, machine feeling better...  With latest software after entering resolve the up and down arrows work but F1 to F4 are skipped as above.  I think perhaps that's because the current sequence is marked with a star.  If I press either Save or Restore then I see 4 blank lines (as in the third picture of the original description).  F1 to F4 switch title labels but I continue to see just 4 blank lines.

**Comment by mpogue2** [comment] 2023-03-20 02:55
NOTE: resolve is currently pretty broken.  I know the source of the problem, but I don't yet understand how to fix it.

ROOT CAUSE:
- on_sd_awaiting_input() assumes that the last line seen from SD always has a blank call, e.g. "3:".  So, it suppresses that (which is correct during most normal usage).
- unfortunately, during a resolve, the last line seen from SD contains **the call needed to resolve the square** (it's NOT empty), and so that gets suppressed, UNTIL we "accept current choice".
- BUT, even then, although the resolve call now appears, the formation associated with the second to last call is now identical to the formation associated with the last call, which is now incorrect.
- This is fixed by SAVE, at which time all the calls appear, and they all have the right formations (you can click on them all, and they are correct).

I tried (and failed) to correct this.  It's really easy to get into a situation where extra blank entries appear in the Current Sequence pane, or the whole app crashes, because there is a tableWidgetCurrentSequenceItem that has no text, and so trying to even qDebug() print that out crashes the whole app.  Or, Revert stops working properly, etc.

Changing this line in on_sd_awaiting_input:
    ui->tableWidgetCurrentSequence->setRowCount(rowCount);
to
    ui->tableWidgetCurrentSequence->setRowCount(sdLastLine);

does not work.
I also tried keeping track of how many "non-empty" entries there were:
    ui->tableWidgetCurrentSequence->setRowCount(sdLastNonEmptyLine); // doesn't work either

As a side note, there are way too many options in the Options tab during a resolve, and I suspect many of these are identical, e.g. "abort the search", "exit the search", "quit the search", and "undo the search".  This pushes the important ones ("find another") down to where they can't be seen without scrolling.  We could cull these to make this more usable.

**Closed** 2023-03-20 04:03 UTC

**Comment by mpogue2** [comment] 2023-03-20 04:06
OK, I think I fixed it (partially) by: 14423969748a49a7f485aab449176f6f86369897 .

This fixes #774, modulo a bug around SAVEing before the resolve has been accepted (which will cause major problems).  Committing this, because it's better than what we have now.

If you type RESOLVE, then be sure to double click "accept current choice" before you SAVE, or hilarity will ensue.

Also, there's still a bug with not rendering the second-to-last call properly until after the SAVE (so if you click on it, you get the resolve picture, not the original picture).  I bet this is related to these lines in on_sd_awaiting_input:

`// In failed subsidiary call cases we don't get a formation output, so we need to manually reset the formation display.`

**Comment by mpogue2** [comment] 2023-03-20 04:08
TODO:
1. fix render of final call in resolve
2. cull the options down to the ones that we can easily click on (or reorder them?)

**Comment by mpogue2** [comment] 2023-03-20 06:29
BUG: UNDO was fixed, but REDO is broken.  DO NOT USE REDO RIGHT NOW.  It will mess up the saved sequence file.
